---
collections:
  - name: ansible.controller
    version: 4.1.1
  - redhat_cop.controller_configuration
  #linux
  - redhat.insights
  - redhat.rhel_system_roles
  - community.general
  - containers.podman
  #windows
  - chocolatey.chocolatey
  - community.windows
  #
  - azure.azcollection
