---
collections:
  - name: awx.awx
  - name: redhat_cop.controller_configuration
    version: 2.1.1
  #linux
  - redhat.insights
  - redhat.rhel_system_roles
  - community.general
  - containers.podman
  #windows
  - chocolatey.chocolatey
  - community.windows
  #
  - azure.azcollection
