---
- name: Podman
  hosts: "{{ HOSTS }}"
  become: yes
  vars:
    volume_path: "{{ ansible_env.HOME }}"
    message: undef

  tasks:
  - name: Install Podman
    ansible.builtin.dnf:
      name: podman
      state: latest
    become: yes

  - name: Create volume dir
    ansible.builtin.file:
      path: "{{ volume_path }}"
      state: directory

  - name: Create index.html
    ansible.builtin.copy:
      dest: "{{ volume_path }}/index.html"
      content: "{{ message }}"

  - name: file permissions
    shell: "chmod -R 775 {{ volume_path }} && chown -R 775:775 {{ volume_path }}"

  - name: Run httpd container
    containers.podman.podman_container:
      name: apache
      image: docker.io/httpd
      state: started
      volume:
        - "{{ volume_path }}:/usr/local/apache2/htdocs"
      ports:
        - "8080:80"

  - name: Check Web Page
    shell: curl http://127.0.0.1:8080
    register: web_output
    changed_when: false

  - name: podman ps
    shell: podman ps
    register: podman_output
    changed_when: false

  - name: Output
    ansible.builtin.debug:
      msg: 
        - "{{ podman_output.stdout_lines }}"
        - "{{ web_output.stdout_lines }}"