---
- name: Podman
  hosts: "{{ HOSTS }}"
  become: yes
  vars:
    volume_path: "{{ ansible_env.HOME }}"
    message: undef

  tasks:
  - name: Install Podman
    ansible.builtin.dnf:
      name: podman
      state: latest
    become: yes

  - name: Run httpd container
    containers.podman.podman_container:
      name: apache
      image: docker.io/httpd
      state: started
      ports:
        - "8080:80"

  - name: Check Web Page
    shell: podman exec apache echo {{ message }} > /usr/local/apache2/htdocs/index.html
    register: web_output
    changed_when: false

  - name: Check Web Page
    shell: curl http://127.0.0.1:8080/index.html
    register: web_output
    changed_when: false

  - name: podman ps
    shell: podman ps
    register: podman_output
    changed_when: false

  - name: Output
    ansible.builtin.debug:
      msg: 
        - "{{ podman_output.stdout_lines }}"
        - "{{ web_output.stdout_lines }}"